"""initial schema: farms, irrigation_logs, cold_storages

Revision ID: a6781bae02f2
Revises: 
Create Date: 2026-08-29 11:42:41.786295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6781bae02f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_telegram_chat_id'), 'farms', ['telegram_chat_id'], unique=True)
    op.create_table('irrigation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('advisory_date', sa.String(), nullable=False),
    sa.Column('t_max_c', sa.Float(), nullable=False),
    sa.Column('t_min_c', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('et0_mm_day', sa.Float(), nullable=False),
    sa.Column('kc', sa.Float(), nullable=False),
    sa.Column('etc_mm_day', sa.Float(), nullable=False),
    sa.Column('effective_rainfall_mm', sa.Float(), nullable=False),
    sa.Column('net_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('should_irrigate', sa.Boolean(), nullable=False),
    sa.Column('recommendation_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_logs_farm_id'), 'irrigation_logs', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_logs_farm_id'), table_name='irrigation_logs')
    op.drop_table('irrigation_logs')
    op.drop_index(op.f('ix_farms_telegram_chat_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('cold_storages')
    # ### end Alembic commands ###
